
data_dir: "./data"
library_dir: "library"
variants_filename: "" # VCF
genes_filename: "" # GTF
geneinfo_filename: ""
sequence_filename: "" # FASTA
variant_sequence_filename: "" # FASTQ


other_paths:
  repeatmasker_path: ""
  dfam_path: ""
  clinvar_path: ""
  jaspar_path: ""
